DA: false
LPN: false
adain: a
alpha: 1.0
batchsize: 8
block: 4
btnk:
- 0
- 1
- 1
- 0
- 0
- 0
- 0
circle: false
color_jitter: false
conv_norm: none
data_dir: "/home/servml/\u0414\u043E\u043A\u0443\u043C\u0435\u043D\u0442\u044B/code/Vladimir/Musenet/University-Release/train"
droprate: 0.5
erasing_p: 0
experiment_name: three_view_long_share_d0.5_256_s1_google_lr0.005_spade_v24.11_210ep_weather_0110000_alpha1_test
extra_Google: true
fp16: false
gpu_ids: '0'
h: 256
iaa: true
lr: 0.005
moving_avg: 1.0
multi_weather: true
name: three_view_long_share_d0.5_256_s1_google_lr0.005_spade_v24.11_210ep_weather_0110000_alpha1_test
nclasses: 701
norm: spade
pad: 10
pool: avg
resume: false
seed: 1
share: true
stride: 1
style_loss: false
train_all: false
use_NAS: false
use_dense: false
use_res101: false
use_vgg: false
views: 3
w: 256
warm_epoch: 0
